common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from jumun import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('jumun/', include('jumun.urls')),
##    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

jumun/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'jumun'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.jumun_create, name='jumun_create'),
    path('delete/', views.jumun_delete, name='jumun_delete'),
    path('excel/', views.jumun_excel, name='jumun_excel'),
    path('excel2/', views.jumun_excel2, name='jumun_excel2'),
    path('tdupdate/', views.jumun_td_update, name='jumun_td_update'),
##    path('upload/', views.uploadFile, name="uploadFile"),
    path('excelupload2/', views.excel_upload, name="excel_upload"),
    path('alldelete/', views.all_delete, name="alldelete"),
    path('order/', views.order_list, name="order"),
    path('order/delete/', views.order_delete, name="order_delete"),
    path('order/excel/', views.order_excel, name="order_excel"),
    path('order/excel2/', views.order_excel2, name="order_excel2"),
    path('order/alldelete/', views.order_all_delete, name="order_alldelete"),
    path('order_submit/', views.order_submit, name="order_submit"),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
     # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Q, Count
from ..models import Question, Answer, Comment, QuestionCount
from ..forms import QuestionForm, AnswerForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import date, datetime, timedelta


# Create your views here.

def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')
    so = request.GET.get('so','recent') #정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')
        
    #검색
    
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력

    """
    question = get_object_or_404(Question, pk=question_id)
   
    context = {'question': question}
    
    response= render(request, 'pybo/question_detail.html', context)

    # 조회수 기능(쿠키이용)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -=now
    max_age = expire_date.total_seconds()

    cookie_value = request.COOKIES.get('hitboard','_')

    if f'_{question_id}_' not in  cookie_value:
        cookie_value += f'{question_id}_'
        response.set_cookie('hitboard', value=cookie_value, max_age=max_age,  httponly=True)
        question.view_count +=1
        question.save()
    return response

#ip 체크 함
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

templates/백업/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no user-scalable=yes">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>파이보</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/백업/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light  border-bottom" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'jumun:index' %}"> Girin-주문장</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
               <li class="nav-item ">
			{% if user.is_authenticated %}
			 <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
			{% else %}
             <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
			{% endif %}
            </li>
        </ul>
    </div>

	<div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="/pybo"><i class="fa-solid fa-book-open-reader"></i> 게시판</a>
                </li>
				
                <li class="nav-item ">
                    <a class="nav-link" href="/jumun/order"><i class="fas fa-history"></i> Order</a>
                </li> 
                
                <li class="nav-item ">
                    <a class="nav-link" href="/common/login/"><i class="fas fa-sign-in-alt"></i> 로그인</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="/common/signup/"><i class="fas fa-user-plus"></i> 회원가입</a>
                </li>
                
            </ul>
        </div>


</nav>